<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UniversitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Kosongkan tabel terlebih dahulu untuk menghindari data duplikat
        DB::table('universities')->truncate();

        // Siapkan data universitas dalam bentuk array
        $universities = [
            ['name' => 'Universitas Nusa Putra', 'domain' => 'nusaputra.ac.id', 'website' => 'https://nusaputra.ac.id', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Akademi Farmasi Mitra Sehat Mandiri Sidoarjo', 'domain' => 'akfarmitseda.ac.id', 'website' => 'http://www.akfarmitseda.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Institut Sains & Teknologi Akprind', 'domain' => 'akprind.ac.id', 'website' => 'http://www.akprind.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'STMIK AMIKOM Yogyakarta', 'domain' => 'amikom.ac.id', 'website' => 'http://www.amikom.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'STIKES RS Anwar Medika', 'domain' => 'stikesrsanwarmedika.ac.id', 'website' => 'http://www.stikesrsanwarmedika.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Katolik Indonesia Atma Jaya', 'domain' => 'atmajaya.ac.id', 'website' => 'http://www.atmajaya.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Bakrie', 'domain' => 'bakrie.ac.id', 'website' => 'http://www.bakrie.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Binus University', 'domain' => 'binus.ac.id', 'website' => 'http://www.binus.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'STIKES Bina Sehat PPNI Mojokerto', 'domain' => 'stikes-ppni.ac.id', 'website' => 'http://www.stikes-ppni.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Bung Hatta', 'domain' => 'bunghatta.ac.id', 'website' => 'http://www.bunghatta.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Dian Nuswantoro', 'domain' => 'dinus.ac.id', 'website' => 'http://www.dinus.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Gunadarma', 'domain' => 'gunadarma.ac.id', 'website' => 'http://www.gunadarma.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Ibn Chaldun Jakarta', 'domain' => 'ibnuchaldun.ac.id', 'website' => 'http://www.ibnuchaldun.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Indonusa Esa Unggul', 'domain' => 'indonusa.ac.id', 'website' => 'http://www.indonusa.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Bogor Agricultural University', 'domain' => 'ipb.ac.id', 'website' => 'http://www.ipb.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Institut Sains dan Teknologi Al Kamal', 'domain' => 'ista.ac.id', 'website' => 'http://www.ista.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Institut Teknologi Adhi Tama Surabaya', 'domain' => 'itats.ac.id', 'website' => 'http://www.itats.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Institut Teknologi Bandung', 'domain' => 'itb.ac.id', 'website' => 'http://www.itb.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Institut Teknologi Sepuluh Nopember', 'domain' => 'its.ac.id', 'website' => 'http://www.its.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Janabadra', 'domain' => 'janabadra.ac.id', 'website' => 'http://www.janabadra.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Jayabaya', 'domain' => 'jayabaya.ac.id', 'website' => 'http://www.jayabaya.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Ma Chung', 'domain' => 'machung.ac.id', 'website' => 'http://www.machung.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Maarif Hasyim Latif', 'domain' => 'umaha.ac.id', 'website' => 'http://www.umaha.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Mahendradatta', 'domain' => 'mahendradatta.org', 'website' => 'http://www.mahendradatta.org/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Negeri Malang', 'domain' => 'um.ac.id', 'website' => 'http://www.um.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Kristen Maranatha', 'domain' => 'maranatha.edu', 'website' => 'http://www.maranatha.edu/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Mercu Buana', 'domain' => 'mercubuana.ac.id', 'website' => 'http://www.mercubuana.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Dr. R. Moestopo', 'domain' => 'moestopo.ac.id', 'website' => 'http://www.moestopo.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Narotama', 'domain' => 'narotama.ac.id', 'website' => 'http://www.narotama.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas HKBP Nommensen', 'domain' => 'nommensen.org', 'website' => 'http://www.nommensen.org/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Pembangunan Panca Budi', 'domain' => 'pancabudi.ac.id', 'website' => 'http://www.pancabudi.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Paramadina Mulya', 'domain' => 'paramadina.ac.id', 'website' => 'http://www.paramadina.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Nasional Pasim', 'domain' => 'pasim.ac.id', 'website' => 'http://www.pasim.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'STIE Perbanas', 'domain' => 'perbanas.ac.id', 'website' => 'http://www.perbanas.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Perbanas Institute', 'domain' => 'perbanas.id', 'website' => 'http://perbanas.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Kristen Petra', 'domain' => 'petra.ac.id', 'website' => 'http://www.petra.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Prasetiya Mulya Business School', 'domain' => 'pmbs.ac.id', 'website' => 'http://www.pmbs.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Politeknik Negeri Jakarta', 'domain' => 'pnj.ac.id', 'website' => 'http://www.pnj.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Politeknik Negeri Lhokseumawe', 'domain' => 'pnl.ac.id', 'website' => 'http://www.pnl.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Politeknik Negeri Bandung', 'domain' => 'polban.ac.id', 'website' => 'http://www.polban.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Politeknik Negeri Semarang', 'domain' => 'polines.ac.id', 'website' => 'http://www.polines.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Politeknik Negeri Padang', 'domain' => 'polinpdg.ac.id', 'website' => 'http://www.polinpdg.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Politeknik Negeri Pontianak', 'domain' => 'polnep.ac.id', 'website' => 'http://www.polnep.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Politeknik Negeri Malang', 'domain' => 'poltek-malang.ac.id', 'website' => 'http://www.poltek-malang.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Politeknik Pos Indonesia', 'domain' => 'poltekpos.ac.id', 'website' => 'http://www.poltekpos.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Politeknik Negeri Sambas', 'domain' => 'poltesa.ac.id', 'website' => 'http://www.poltesa.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Putera Batam', 'domain' => 'puterabatam.ac.id', 'website' => 'http://www.puterabatam.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Sarjanawiyata Tamansiswa', 'domain' => 'sarjanawiyata.ac.id', 'website' => 'http://www.sarjanawiyata.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Swiss German University', 'domain' => 'sgu.ac.id', 'website' => 'http://www.sgu.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'STMIK Sinar Nusantara', 'domain' => 'sinus.ac.id', 'website' => 'http://www.sinus.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Sekolah Tinggi Akuntansi Negara (STAN)', 'domain' => 'stan.ac.id', 'website' => 'http://www.stan.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Trisakti Institute of Tourism', 'domain' => 'stptrisakti.ac.id', 'website' => 'http://www.stptrisakti.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Telkom', 'domain' => 'telkomuniversity.ac.id', 'website' => 'http://www.telkomuniversity.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Klabat', 'domain' => 'unklab.ac.id', 'website' => 'http://www.unklab.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Trisakti', 'domain' => 'trisakti.ac.id', 'website' => 'http://www.trisakti.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Ahmad Dahlan', 'domain' => 'uad.ac.id', 'website' => 'http://www.uad.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Atma Jaya Yogyakarta', 'domain' => 'uajy.ac.id', 'website' => 'http://www.uajy.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Brawijaya', 'domain' => 'ub.ac.id', 'website' => 'http://www.ub.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Surabaya', 'domain' => 'ubaya.ac.id', 'website' => 'http://www.ubaya.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Bhayangkara Surabaya', 'domain' => 'ubhara.ac.id', 'website' => 'http://www.ubhara.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Bhayangkara Jakarta Raya', 'domain' => 'ubharajaya.ac.id', 'website' => 'http://www.ubharajaya.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Bunda Mulia Jakarta', 'domain' => 'ubm.ac.id', 'website' => 'http://www.ubm.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Darma Agung', 'domain' => 'uda.ac.id', 'website' => 'http://www.uda.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Gadjah Mada', 'domain' => 'ugm.ac.id', 'website' => 'http://www.ugm.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Indonesia', 'domain' => 'ui.ac.id', 'website' => 'http://www.ui.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Islam Indonesia', 'domain' => 'uii.ac.id', 'website' => 'http://www.uii.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Ibn Khaldun Bogor', 'domain' => 'uika-bogor.ac.id', 'website' => 'http://www.uika-bogor.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Islam Jakarta', 'domain' => 'uinjkt.ac.id', 'website' => 'http://www.uinjkt.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Islam Riau', 'domain' => 'uir.ac.id', 'website' => 'http://www.uir.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Islam Sumatera Utara', 'domain' => 'uisu.ac.id', 'website' => 'http://www.uisu.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Kristen Duta Wacana', 'domain' => 'ukdw.ac.id', 'website' => 'http://www.ukdw.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Kristen Indonesia', 'domain' => 'uki.ac.id', 'website' => 'http://www.uki.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Kristen Indonesia Tomohon', 'domain' => 'ukit-tomohon.org', 'website' => 'http://www.ukit-tomohon.org/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Kristen Krida Wacana', 'domain' => 'ukrida.ac.id', 'website' => 'http://www.ukrida.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Kristen Satya Wacana', 'domain' => 'uksw.edu', 'website' => 'http://www.uksw.edu/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Muslim Indonesia', 'domain' => 'umi.ac.id', 'website' => 'http://www.umi.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Methodist Indonesia', 'domain' => 'umi-mdn.edu', 'website' => 'http://www.umi-mdn.edu/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Muhammadiyah Jakarta', 'domain' => 'umj.ac.id', 'website' => 'http://www.umj.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Muria Kudus', 'domain' => 'umk.ac.id', 'website' => 'http://www.umk.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Muhammadiyah Malang', 'domain' => 'umm.ac.id', 'website' => 'http://www.umm.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Muhammadiyah Magelang', 'domain' => 'ummgl.ac.id', 'website' => 'http://www.ummgl.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Muhammadiyah Sidoarjo', 'domain' => 'umsida.ac.id', 'website' => 'http://www.umsida.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Muhammadiyah Surakarta', 'domain' => 'ums.ac.id', 'website' => 'http://www.ums.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Muhammadiyah Sumatra Utara', 'domain' => 'umsu.ac.id', 'website' => 'http://www.umsu.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Muhammadiyah Yogyakarta', 'domain' => 'umy.ac.id', 'website' => 'http://www.umy.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Advent Indonesia', 'domain' => 'unai.edu', 'website' => 'http://www.unai.edu/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Airlangga', 'domain' => 'unair.ac.id', 'website' => 'http://www.unair.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Andalas', 'domain' => 'unand.ac.id', 'website' => 'http://www.unand.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Nasional Jakarta', 'domain' => 'unas.ac.id', 'website' => 'http://www.unas.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Cenderawasih', 'domain' => 'uncen.ac.id', 'website' => 'http://www.uncen.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Nusa Cendana', 'domain' => 'undana.ac.id', 'website' => 'http://www.undana.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Diponegoro', 'domain' => 'undip.ac.id', 'website' => 'http://www.undip.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Jember', 'domain' => 'unej.ac.id', 'website' => 'http://www.unej.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Negeri Surabaya', 'domain' => 'unesa.ac.id', 'website' => 'http://www.unesa.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Negeri Gorontalo', 'domain' => 'ung.ac.id', 'website' => 'http://www.ung.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Haluoleo', 'domain' => 'unhalu.ac.id', 'website' => 'http://www.unhalu.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Amir Hamzah', 'domain' => 'unhamzah.ac.id', 'website' => 'http://www.unhamzah.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Hasanuddin', 'domain' => 'unhas.ac.id', 'website' => 'http://www.unhas.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Bengkulu', 'domain' => 'unib.ac.id', 'website' => 'http://www.unib.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Bojonegoro', 'domain' => 'unigoro.ac.id', 'website' => 'http://www.unigoro.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Katolik Soegijapranoto', 'domain' => 'unika.ac.id', 'website' => 'http://www.unika.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Pekalongan', 'domain' => 'unikal.ac.id', 'website' => 'http://www.unikal.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Kediri', 'domain' => 'unik-kediri.ac.id', 'website' => 'http://www.unik-kediri.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Komputer Indonesia', 'domain' => 'unikom.ac.id', 'website' => 'http://www.unikom.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Lampung', 'domain' => 'unila.ac.id', 'website' => 'http://www.unila.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Lancang Kuning', 'domain' => 'unilak.ac.id', 'website' => 'http://unilak.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Negeri Manado', 'domain' => 'unima.ac.id', 'website' => 'http://www.unima.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Negeri Medan', 'domain' => 'unimed.ac.id', 'website' => 'http://www.unimed.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Islam Nusantara', 'domain' => 'uninus.ac.id', 'website' => 'http://www.uninus.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Pesantren Darul Ulum Jombang', 'domain' => 'unipdu.ac.id', 'website' => 'http://www.unipdu.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Madura', 'domain' => 'unira.ac.id', 'website' => 'http://www.unira.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Islam Bandung', 'domain' => 'unisba.ac.id', 'website' => 'http://www.unisba.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Islam Malang', 'domain' => 'unisma.ac.id', 'website' => 'http://www.unisma.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Muhammadiyah Makassar', 'domain' => 'unismuh.ac.id', 'website' => 'http://www.unismuh.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Slamet Riyadi Surakarta', 'domain' => 'unisri.ac.id', 'website' => 'http://www.unisri.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Islam Sultan Agung', 'domain' => 'unissula.ac.id', 'website' => 'http://www.unissula.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Islam Syekh-Yusuf', 'domain' => 'unistangerang.ac.id', 'website' => 'http://www.unistangerang.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Unitomo Surabaya', 'domain' => 'unitomo.ac.id', 'website' => 'http://www.unitomo.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Trilogi', 'domain' => 'universitas-trilogi.ac.id', 'website' => 'http://www.universitas-trilogi.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Trunojoyo Madura', 'domain' => 'trunojoyo.ac.id', 'website' => 'http://www.trunojoyo.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Pancasila', 'domain' => 'univpancasila.ac.id', 'website' => 'http://www.univpancasila.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas PGRI Adi Buana Surabaya', 'domain' => 'unipasby.ac.id', 'website' => 'http://www.unipasby.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Jambi', 'domain' => 'unja.ac.id', 'website' => 'http://www.unja.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Negeri Jakarta', 'domain' => 'unj.ac.id', 'website' => 'http://www.unj.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Jenderal Achmad Yani', 'domain' => 'unjani.ac.id', 'website' => 'http://www.unjani.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Khairun', 'domain' => 'unkhair.ac.id', 'website' => 'http://www.unkhair.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Krisnadwipayana', 'domain' => 'unkris.ac.id', 'website' => 'http://www.unkris.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Lambung Mangkurat', 'domain' => 'unlam.ac.id', 'website' => 'http://www.unlam.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Negeri Makassar', 'domain' => 'unm.ac.id', 'website' => 'http://www.unm.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Mahasaraswati Denpasar', 'domain' => 'unmas.org', 'website' => 'http://www.unmas.org/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Merdeka Malang', 'domain' => 'unmer.ac.id', 'website' => 'http://www.unmer.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Merdeka Madiun', 'domain' => 'unmer-madiun.ac.id', 'website' => 'http://www.unmer-madiun.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Muhammadiyah Jember', 'domain' => 'unmuhjember.ac.id', 'website' => 'http://www.unmuhjember.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Muhammadiyah Mataram', 'domain' => 'unmuhmataram.com', 'website' => 'http://www.unmuhmataram.com/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Mulawarman', 'domain' => 'unmul.ac.id', 'website' => 'http://www.unmul.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'STMIK Widya Cipta Dharma', 'domain' => 'wicida.ac.id', 'website' => 'http://www.wicida.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Negeri Semarang', 'domain' => 'unnes.ac.id', 'website' => 'http://www.unnes.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Negeri Padang', 'domain' => 'unp.ac.id', 'website' => 'http://www.unp.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Padjadjaran', 'domain' => 'unpad.ac.id', 'website' => 'http://www.unpad.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Pakuan', 'domain' => 'unpak.ac.id', 'website' => 'http://www.unpak.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Katolik Parahyangan', 'domain' => 'unpar.ac.id', 'website' => 'http://www.unpar.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Pasundan', 'domain' => 'unpas.ac.id', 'website' => 'http://www.unpas.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Pattimura', 'domain' => 'unpatti.ac.id', 'website' => 'http://www.unpatti.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Ngurah Rai', 'domain' => 'unr.ac.id', 'website' => 'http://www.unr.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Mataram', 'domain' => 'unram.ac.id', 'website' => 'http://www.unram.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Riau', 'domain' => 'unri.ac.id', 'website' => 'http://www.unri.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Sebelas Maret', 'domain' => 'uns.ac.id', 'website' => 'http://www.uns.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Darma Persada', 'domain' => 'unsada.ac.id', 'website' => 'http://www.unsada.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Siliwangi', 'domain' => 'unsil.ac.id', 'website' => 'http://www.unsil.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Jenderal Soedirman', 'domain' => 'unsoed.ac.id', 'website' => 'http://www.unsoed.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Sam Ratulangi', 'domain' => 'unsrat.ac.id', 'website' => 'http://www.unsrat.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Sriwijaya', 'domain' => 'unsri.ac.id', 'website' => 'http://www.unsri.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Swadaya Gunung Djati', 'domain' => 'unswagati-crb.ac.id', 'website' => 'http://www.unswagati-crb.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Syiah Kuala', 'domain' => 'unsyiah.ac.id', 'website' => 'http://www.unsyiah.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Tadulako', 'domain' => 'untad.ac.id', 'website' => 'http://www.untad.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas 17 Agustus 1945 Surabaya', 'domain' => 'untag.ac.id', 'website' => 'http://www.untag.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas 17 Agustus 1945 Banyuwangi', 'domain' => 'untag-banyuwangi.ac.id', 'website' => 'http://www.untag-banyuwangi.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas 17 Agustus 1945 Cirebon', 'domain' => 'untagcirebon.info', 'website' => 'http://www.untagcirebon.info/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas 17 Agustus 1945 Jakarta', 'domain' => 'untag-jkt.org', 'website' => 'http://www.untag-jkt.org/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas 17 Agustus 1945 Samarinda', 'domain' => 'untag-smd.ac.id', 'website' => 'http://www.untag-smd.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas 17 Agustus 1945 Semarang', 'domain' => 'untagsmg.ac.id', 'website' => 'http://www.untagsmg.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Tanjungpura', 'domain' => 'untan.ac.id', 'website' => 'http://www.untan.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Tarumanagara', 'domain' => 'untar.ac.id', 'website' => 'http://www.untar.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Sultan Ageng Tirtayasa', 'domain' => 'untirta.ac.id', 'website' => 'http://www.untirta.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Udayana', 'domain' => 'unud.ac.id', 'website' => 'http://www.unud.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Wijaya Kusuma Purwokerto', 'domain' => 'unwiku.ac.id', 'website' => 'http://www.unwiku.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Negeri Yogyakarta', 'domain' => 'uny.ac.id', 'website' => 'http://www.uny.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Proklamasi 45', 'domain' => 'up45.ac.id', 'website' => 'http://www.up45.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Pelita Harapan', 'domain' => 'uph.edu', 'website' => 'http://www.uph.edu/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Pendidikan Indonesia', 'domain' => 'upi.edu', 'website' => 'http://www.upi.edu/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Pembangunan Nasional "Veteran" Jakarta', 'domain' => 'upnvj.ac.id', 'website' => 'http://www.upnvj.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Pembangunan Nasional "Veteran" Jawa Timur', 'domain' => 'upnjatim.ac.id', 'website' => 'http://www.upnjatim.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Pembangunan Nasional "Veteran" Yogyakarta', 'domain' => 'upnyk.ac.id', 'website' => 'http://www.upnyk.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Palangka Raya', 'domain' => 'upr.ac.id', 'website' => 'http://www.upr.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Pancasakti Tegal', 'domain' => 'upstegal.ac.id', 'website' => 'http://www.upstegal.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Sanata Dharma', 'domain' => 'usd.ac.id', 'website' => 'http://www.usd.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Simalungun', 'domain' => 'usi.ac.id', 'website' => 'http://www.usi.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Semarang', 'domain' => 'usm.ac.id', 'website' => 'http://www.usm.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Sumatera Utara', 'domain' => 'usu.ac.id', 'website' => 'http://www.usu.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Terbuka Indonesia', 'domain' => 'ut.ac.id', 'website' => 'http://www.ut.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Tidar Magelang', 'domain' => 'untidar.ac.id', 'website' => 'http://www.untidar.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Tunas Pembangunan', 'domain' => 'utp.ac.id', 'website' => 'http://www.utp.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Widya Gama Malang', 'domain' => 'widyagama.ac.id', 'website' => 'http://www.widyagama.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Katolik Widya Karya', 'domain' => 'widyakarya.ac.id', 'website' => 'http://www.widyakarya.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Widyatama', 'domain' => 'widyatama.ac.id', 'website' => 'http://www.widyatama.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Wijaya Kusuma Surabaya', 'domain' => 'wijayakusumasby.ac.id', 'website' => 'http://www.wijayakusumasby.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Katolik Widya Manadala', 'domain' => 'wima.ac.id', 'website' => 'http://www.wima.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Wisnuwardhana', 'domain' => 'wisnuwardhana.ac.id', 'website' => 'http://www.wisnuwardhana.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Persada Indonesia Y.A.I', 'domain' => 'yai.ac.id', 'website' => 'http://www.yai.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Universitas Yarsi', 'domain' => 'yarsi.ac.id', 'website' => 'http://www.yarsi.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Duta Bangsa University', 'domain' => 'udb.ac.id', 'website' => 'https://udb.ac.id/', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
            ['name' => 'Akademi Farmasi Yarsis Pekanbaru', 'domain' => 'akfaryarsiptk.ac.id', 'website' => 'https://akfaryarsiptk.ac.id', 'alpha_code' => 'ID', 'country' => 'Indonesia', 'province' => null],
        ];

        // Masukkan data ke dalam tabel 'universitas'
        DB::table('universities')->insert($universities);
    }
}